import type { Metadata } from 'next';

import './globals.css';
import Sidebar from '@/components/Sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-[#0D0C1D] text-white">
        <Sidebar />
        <div className="flex min-h-screen flex-1 flex-col overflow-hidden">
          <main className="flex-1 overflow-auto p-2">{children}</main>
        </div>
      </body>
    </html>
  );
}
