import type { Metadata } from 'next';

import './globals.css';
import Sidebar from '@/components/Sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0D0C1D] text-white flex">
        <Sidebar />
        <div className="flex flex-col flex-1 min-h-screen overflow-hidden">
          <main className="flex-1 p-2 overflow-auto ">{children}</main>
        </div>
      </body>
    </html>
  );
}
